var images = [
  'images/ebryn.jpg',
  'images/iterzic.jpg',
  'images/kselden.jpg',
  'images/machty.jpg',
  'images/rwjblue.jpg',
  'images/stefanpenner.jpg',
  'images/tomdale.jpg',
  'images/trek.jpg',
  'images/wagenet.jpg',
  'images/wycats.jpg',
];

var smallImages = [
  'images/small/Ba_Gua_Feng-Shui-Mirror.gif',
  'images/small/Bonsai.gif',
  'images/small/Chouchin_Reinensai_Lantern.gif',
  'images/small/Chouchin_Kuroshiro_Lantern_.gif',
  'images/small/Chouchin_Shinku_Lantern.gif',
  'images/small/Fuurin_Glass_Wind_Chime.gif',
  'images/small/Geta_Wooden_Sandal_.gif',
  'images/small/Gunsen_Fan_.gif',
  'images/small/iChing_Kouka_Heads-Coin.gif',
  'images/small/iChing_Kouka_Tails_Coin.gif',
  'images/small/Ishidourou_Snow_Lantern.gif',
  'images/small/Kakejiku_Hanging_Scroll.gif',
  'images/small/Katana_and_Sheath.gif',
  'images/small/Kimono_Buru_Blue.gif',
  'images/small/Kimono_Chairo_Tan.gif',
  'images/small/Koi.gif',
  'images/small/Shamisen.gif',
  'images/small/Shodou_Calligraphy.gif',
  'images/small/Torii.gif',
  'images/small/Tsukubai_Water_Basin.gif',
];

var strangeRatios = [
  'images/strange-ratios/horizontal-rectangle.jpg',
  'images/strange-ratios/square.jpg',
  'images/strange-ratios/vertical-rectangle.jpg',
];

var remoteImages = [
  'http://placekitten.com/50/50',
  'http://placekitten.com/51/50',
  'http://placekitten.com/52/50',
  'http://placekitten.com/53/50',
  'http://placekitten.com/54/50',
  'http://placekitten.com/55/50',
  'http://placekitten.com/56/50',
  'http://placekitten.com/57/50',
  'http://placekitten.com/58/50',
  'http://placekitten.com/59/50',
  'http://placekitten.com/50/51',
  'http://placekitten.com/50/52',
  'http://placekitten.com/50/53',
  'http://placekitten.com/50/54',
  'http://placekitten.com/50/55',
  'http://placekitten.com/50/56',
  'http://placekitten.com/50/57',
  'http://placekitten.com/50/58',
  'http://placekitten.com/50/59',
  'http://placekitten.com/60/50',
  'http://placekitten.com/61/50',
  'http://placekitten.com/62/50',
  'http://placekitten.com/63/50',
  'http://placekitten.com/64/50',
  'http://placekitten.com/65/50',
  'http://placekitten.com/66/50',
  'http://placekitten.com/67/50',
  'http://placekitten.com/68/50',
  'http://placekitten.com/69/50',
  'http://placekitten.com/50/60',
  'http://placekitten.com/50/61',
  'http://placekitten.com/50/62',
  'http://placekitten.com/50/63',
  'http://placekitten.com/50/64',
  'http://placekitten.com/50/65',
  'http://placekitten.com/50/66',
  'http://placekitten.com/50/67',
  'http://placekitten.com/50/68',
  'http://placekitten.com/50/69',
];

export default { images, smallImages, strangeRatios, remoteImages };
